server:
  port: 8020

spring:
  application:
    name: order-service

  cloud:
    nacos:
      server-addr: 192.168.200.130:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
